-- remove all connections to the target db
-- SELECT pg_terminate_backend(pg_stat_activity.pid)
-- FROM pg_stat_activity
-- WHERE pg_stat_activity.datname = 'ustart_db' -- ← change this to your DB
--   AND pid <> pg_backend_pid();
-------------------------------------------------------------------------------

-- drop database ustart_db;

-- create database ustart_db;

-- user
DROP TABLE IF EXISTS "user";

CREATE TABLE "public"."user" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "email" character varying,
    "hashed_password" character varying,
    CONSTRAINT "ix_user_email" UNIQUE ("email"),
    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
) WITH (oids = false);
-------------------------------------------------------------------------------

-- passport
DROP TABLE IF EXISTS "passport";

CREATE TABLE "public"."passport" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "series" character varying(4),
    "number" character varying(6),
    "issued_code" character varying(6),
    "issued_date" date,
    "user_id" integer,
    CONSTRAINT "passport_number_key" UNIQUE ("number"),
    CONSTRAINT "passport_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "passport_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) NOT DEFERRABLE
) WITH (oids = false);
-------------------------------------------------------------------------------

-- entrepreneur
DROP TABLE IF EXISTS "entrepreneur";

CREATE TABLE "public"."entrepreneur" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "first_name" character varying,
    "last_name" character varying,
    "patronymic" character varying,
    "bio" character varying,
    "user_id" integer,
    avatar 
    CONSTRAINT "entrepreneur_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "entrepreneur_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) NOT DEFERRABLE
) WITH (oids = false);
-------------------------------------------------------------------------------

-- investor
DROP TABLE IF EXISTS "investor";

CREATE TABLE "public"."investor" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer,
    "name" character varying,
    "link" character varying,
    "bio" character varying,
    "min_investment" numeric,
    "max_investment" numeric,
    "maximal_historical_investment" numeric,
    "avatar" character varying,
    CONSTRAINT "investor_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "investor_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) NOT DEFERRABLE
) WITH (oids = false);
-------------------------------------------------------------------------------

-- tag
DROP TABLE IF EXISTS "tag";

CREATE TABLE "public"."tag" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying,
    CONSTRAINT "tag_pkey" PRIMARY KEY ("id")
) WITH (oids = false);
-------------------------------------------------------------------------------

-- investor_tag
DROP TABLE IF EXISTS "investor_tag";
CREATE TABLE "public"."investor_tag" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvestorID" integer,
    "TagID" integer,
    CONSTRAINT "investor_tag_InvestorID_fkey" FOREIGN KEY ("InvestorID") REFERENCES investor(id) NOT DEFERRABLE,
    CONSTRAINT "investor_tag_TagID_fkey" FOREIGN KEY ("TagID") REFERENCES tag(id) NOT DEFERRABLE
) WITH (oids = false);
-------------------------------------------------------------------------------

-- investment
DROP TABLE IF EXISTS "investment";

CREATE TABLE "public"."investment" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying,
    "description" character varying,
    "start_date" date,
    "end_date" date,
    "link" character varying,
    "min_money" numeric,
    "max_money" numeric,
    CONSTRAINT "investment_pkey" PRIMARY KEY ("id")
) WITH (oids = false);
-------------------------------------------------------------------------------

-- investorinvestmenthistory
DROP TABLE IF EXISTS "investor_investment_history";

CREATE TABLE "public"."investor_investment_history" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "investor_id" integer,
    "project_name" character varying,
    "link" character varying,
    "money_invested" numeric,
    CONSTRAINT "investorinvestmenthistory_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "investorinvestmenthistory_investor_id_fkey" FOREIGN KEY (investor_id) REFERENCES investor(id) NOT DEFERRABLE
) WITH (oids = false);
-------------------------------------------------------------------------------

-- document
DROP TABLE IF EXISTS "document";

CREATE TABLE "public"."document" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "type" character varying NOT NULL,
    "document_name" character varying NOT NULL,
    "file" character varying NOT NULL,
    CONSTRAINT "document_pkey" PRIMARY KEY ("id")
) WITH (oids = false);
-------------------------------------------------------------------------------

-- startup
DROP TABLE IF EXISTS "startup";

CREATE TABLE "public"."startup" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying,
    "description" character varying,
    "logo" character varying,
    "document_id" integer,
    "owner_id" integer,
    "money_requirement" decimal not null,
    CONSTRAINT "startup_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "startup_document_id_fkey" FOREIGN KEY (document_id) REFERENCES document(id) NOT DEFERRABLE,
    CONSTRAINT "startup_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES entrepreneur(id) NOT DEFERRABLE
) WITH (oids = false);
-------------------------------------------------------------------------------

-- startup_tag
DROP TABLE IF EXISTS "startup_tag";
CREATE TABLE "public"."startup_tag" (
    "StartupID" integer,
    "TagID" integer,
    CONSTRAINT "startup_tag_StartupID_fkey" FOREIGN KEY ("StartupID") REFERENCES startup(id) NOT DEFERRABLE,
    CONSTRAINT "startup_tag_TagID_fkey" FOREIGN KEY ("TagID") REFERENCES tag(id) NOT DEFERRABLE
) WITH (oids = false);
-------------------------------------------------------------------------------
